CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_GPIO=y
CONFIG_LED=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# SPI Flash
CONFIG_ESPTOOLPY_OCT_FLASH=n
CONFIG_ESPTOOLPY_FLASHSIZE_16MB=y

# SPI RAM
CONFIG_ESP_SPIRAM=y
CONFIG_ESP_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_MODE_QUAD=y
CONFIG_SPIRAM_SPEED_40M=y
CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
CONFIG_SPIRAM_RODATA=y

# SPI Flash
#CONFIG_ESPTOOLPY_FLASHFREQ=40m
CONFIG_ESPTOOLPY_FLASHFREQ_40M=y